#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export ZSHRC="$ZDOTDIR/.zshrc"
export XDG_CONFIG_HOME="$HOME/.config"
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export EDITOR="nvim"
export PATH="$HOME/.local/bin":$PATH
export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
export BAT_THEME="Catppuccin-macchiato"

# nap snippet manager config
# export NAP_CONFIG="~/.config/nap/config.yaml"
export NAP_HOME="$HOME/programming/snippets"
export NAP_DEFAULT_LANGUAGE="js"
export NAP_THEME="dracula"

export NIXPKGS_ALLOW_UNFREE=1

export PATH="/Users/howard/Library/Python/3.9/bin:$PATH" #xcode python

export PKM="$HOME/Sync/howard-pkm"
