#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export ZSHRC="$ZDOTDIR/.zshrc"
export XDG_CONFIG_HOME="$HOME/.config"
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export EDITOR="nvim"
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.cargo/bin":$PATH
export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
export BAT_THEME="Catppuccin-macchiato"

export PKM="$HOME/Sync/howard-pkm"
# nap snippet manager config
# export NAP_CONFIG="~/.config/nap/config.yaml"
export NAP_HOME="$PKM/otherapps/nap-snippets"
export NAP_DEFAULT_LANGUAGE="go"
export NAP_THEME="nord"

export NIXPKGS_ALLOW_UNFREE=1

export PATH="/Users/howard/Library/Python/3.9/bin:$PATH" #xcode python

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export PATH="$HOME/flutter/bin":$PATH
export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH="$ANDROID_HOME/tools":$PATH
export PATH="$ANDROID_HOME/tools/bin":$PATH
export PATH="$ANDROID_HOME/platform-tools":$PATH
export PATH="$HOME/go/bin":$PATH
export PATH="$HOME/.local/share/nvim/mason/bin":$PATH # neovim mason

case "$(uname -s)" in
Darwin)
	# echo 'Mac OS X'
  export BROWSER="open"
	;;

Linux)
  export BROWSER="firefox"
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac
