gui:
  theme:
    # catppuccin macchiato {{{
    lightTheme: false 
    activeBorderColor:
      - "#a6da95" # Green
      - bold
    inactiveBorderColor:
      - "#cad3f5" # Text
    optionsTextColor:
      - "#8aadf4" # Blue
    selectedLineBgColor:
      - "#363a4f" # Surface0
    selectedRangeBgColor:
      - "#363a4f" # Surface0
    cherryPickedCommitBgColor:
      - "#8bd5ca" # Teal
    cherryPickedCommitFgColor:
      - "#8aadf4" # Blue
    unstagedChangesColor:
      - red       # Red }}}
    # selectedLineBgColor:
    # - underline
    # selectedRangeBgColor:
    # - underline
git:
  paging:
    colorArg: never
    pager: delta --dark --paging=never
# os:
#   editCommand: 'nvim'
#   editCommandTemplate: '{{editor}} --server /tmp/nvim-server.pipe --remote-tab "$(pwd)/{{filename}}"'
